language: node_js
node_js:
  - "5.1"
  - "5.3"
sudo: false
before_install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
os:
  - linux
  - osx
  - windows
install:
  - npm install
script: "npm test"
